apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-validator
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: route-validator
  template:
    metadata:
      labels:
        app: route-validator
    spec:
      containers:
        - name: route-validator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tls-certs
              mountPath: /certs
              readOnly: true
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: route-validator
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ .Values.tls.existingSecret | default "route-validator-tls" }}