apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-validator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: route-validator
  template:
    metadata:
      labels:
        app: route-validator
    spec:
      containers:
        - name: route-validator
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tls-certs
              mountPath: /certs
              readOnly: true
            - name: config
              mountPath: /etc/route-validator
              readOnly: true
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.deployment.logLevel | quote }}
      serviceAccountName: route-validator
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ .Values.tls.existingSecret | default "route-validator-tls" }}
        - name: config
          configMap:
            name: route-validator-config