apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: route-validator
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "namespaces"]
    verbs: ["get", "list", "watch"]