apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-validator-cr
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]