apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: route-validator
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: route-validator
roleRef:
  kind: Role
  name: route-validator
  apiGroup: rbac.authorization.k8s.io