{{- if not .Values.tls.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: route-validator-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}