apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: route-validator-webhook
  namespace: {{ .Values.namespace }}
webhooks:
  - name: {{ .Values.webhook.name }}
    rules:
      - apiGroups: ["route.openshift.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["routes"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: {{ .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: /validate
        port: {{ .Values.service.port }}
      {{- if .Values.webhook.caBundle }}
      caBundle: {{ .Values.webhook.caBundle | b64enc }}
      {{- end }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: {{ .Values.webhook.failurePolicy }}